

const deleteInvoice = async (req) => {
    try {
    } catch (error: any) {
    }

}

export { deleteInvoice }